#!/bin/bash
# Daily Update Script for Forest's OpenClaw Profile
# Runs at 20:00 daily to update information and sync to GitHub

set -e

WORKSPACE_DIR="/root/.openclaw/workspace"
LOG_FILE="$WORKSPACE_DIR/memory/daily-update-$(date +%Y-%m-%d).log"
CONFIG_FILE="$WORKSPACE_DIR/USER.md"
BACKUP_DIR="$WORKSPACE_DIR/backups"

# Create directories if they don't exist
mkdir -p "$BACKUP_DIR"
mkdir -p "$(dirname "$LOG_FILE")"

echo "=== Daily Update Started: $(date) ===" | tee -a "$LOG_FILE"
echo "User: Forest (Fangcheng Liu)" | tee -a "$LOG_FILE"
echo "Purpose: Update professional profile and sync to GitHub" | tee -a "$LOG_FILE"

# Step 1: Backup current configuration
echo "1. Backing up current configuration..." | tee -a "$LOG_FILE"
BACKUP_FILE="$BACKUP_DIR/user-backup-$(date +%Y%m%d-%H%M%S).md"
cp "$CONFIG_FILE" "$BACKUP_FILE"
echo "   Backup created: $(basename "$BACKUP_FILE")" | tee -a "$LOG_FILE"

# Step 2: Update last updated timestamp in USER.md
echo "2. Updating last updated timestamp..." | tee -a "$LOG_FILE"
CURRENT_DATE=$(date "+%Y-%m-%d")
LAST_UPDATED_LINE="**Last Updated:** $CURRENT_DATE"

if grep -q "^\*\*Last Updated:\*\*" "$CONFIG_FILE"; then
    # Update existing timestamp
    sed -i "s|^\*\*Last Updated:\*\*.*|$LAST_UPDATED_LINE|" "$CONFIG_FILE"
else
    # Add timestamp after basic information section
    sed -i "/## Basic Information/,/^##/ {/^##/i\\
$LAST_UPDATED_LINE
}" "$CONFIG_FILE"
fi

# Step 3: Update daily activity summary
echo "3. Creating daily activity summary..." | tee -a "$LOG_FILE"
DAILY_FILE="$WORKSPACE_DIR/memory/daily-$(date +%Y-%m-%d).md"

cat > "$DAILY_FILE" << EOF
# Daily Activity Summary - $CURRENT_DATE

## Overview
- **Date:** $CURRENT_DATE
- **Update Time:** $(date "+%H:%M")
- **Update Type:** Automated daily sync

## System Status
- OpenClaw workspace: Operational
- GitHub sync: Configured
- Backup: Created

## Updates Applied
1. Updated last modified timestamp in USER.md
2. Created daily activity log
3. Prepared for GitHub synchronization

## Notes
This is an automated daily update. Manual reviews and adjustments may be needed for specific content updates.

---
*Automatically generated by Grove (Forest's Enterprise Architecture Companion)*
EOF

echo "   Daily summary created: $(basename "$DAILY_FILE")" | tee -a "$LOG_FILE"

# Step 4: Git operations
echo "4. Performing Git operations..." | tee -a "$LOG_FILE"
cd "$WORKSPACE_DIR"

# Check if there are changes
if git diff --quiet; then
    echo "   No changes to commit" | tee -a "$LOG_FILE"
else
    # Add all changes
    git add .
    
    # Create commit
    COMMIT_MSG="Daily update: $CURRENT_DATE - Automated profile maintenance"
    git commit -m "$COMMIT_MSG"
    
    # Push to GitHub
    if git push origin main; then
        echo "   Successfully pushed to GitHub" | tee -a "$LOG_FILE"
        echo "   Commit: $COMMIT_MSG" | tee -a "$LOG_FILE"
    else
        echo "   ERROR: Failed to push to GitHub" | tee -a "$LOG_FILE"
        echo "   Check Git configuration and network connectivity" | tee -a "$LOG_FILE"
    fi
fi

# Step 5: Cleanup old backups (keep last 7 days)
echo "5. Cleaning up old backups..." | tee -a "$LOG_FILE"
find "$BACKUP_DIR" -name "user-backup-*.md" -mtime +7 -delete 2>/dev/null || true
BACKUP_COUNT=$(find "$BACKUP_DIR" -name "user-backup-*.md" | wc -l)
echo "   Current backup count: $BACKUP_COUNT (last 7 days retained)" | tee -a "$LOG_FILE"

# Step 6: Update heartbeat state
echo "6. Updating system state..." | tee -a "$LOG_FILE"
if [ -f "$WORKSPACE_DIR/memory/heartbeat-state.json" ]; then
    # Update last daily update timestamp
    TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    sed -i "s/\"lastDailyUpdate\":.*,/\"lastDailyUpdate\": \"$TIMESTAMP\",/" "$WORKSPACE_DIR/memory/heartbeat-state.json" 2>/dev/null || \
    sed -i "/\"preferences\":/i\  \"lastDailyUpdate\": \"$TIMESTAMP\"," "$WORKSPACE_DIR/memory/heartbeat-state.json"
fi

echo "=== Daily Update Completed: $(date) ===" | tee -a "$LOG_FILE"
echo "Summary:" | tee -a "$LOG_FILE"
echo "- Configuration backed up" | tee -a "$LOG_FILE"
echo "- Timestamp updated" | tee -a "$LOG_FILE"
echo "- Daily summary created" | tee -a "$LOG_FILE"
echo "- Git operations completed" | tee -a "$LOG_FILE"
echo "- Old backups cleaned" | tee -a "$LOG_FILE"

exit 0